fos_rest:

    routing_loader:
        default_format: json
        include_format: false

    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json}
            - { path: '^/', priorities: ['text/html', '*/*'], fallback_format: html, prefer_extension: true }
    
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors

    exception:
        enabled: true
        exception_controller: 'fos_rest.exception.controller:showAction'
    
    view:
        view_response_listener: 'force'
        formats:
            json: true